services:
  jekyll:
    image: ruby:3.2-slim
    ports:
      - "4000:4000"
    volumes:
      - .:/srv/jekyll:Z
      - bundle_cache:/usr/local/bundle
    working_dir: /srv/jekyll
    command: >
      bash -c "
        apt-get update && apt-get install -y nodejs git build-essential &&
        bundle install &&
        bundle exec jekyll serve --host 0.0.0.0 --watch --livereload --config '_config.yml,_config.local.yml'
      "
    environment:
      - JEKYLL_ENV=development
      - BUNDLE_PATH=/usr/local/bundle

volumes:
  bundle_cache: