name: cattaneo-site
channels:
  - conda-forge
dependencies:
  - ruby=3.3
  - nodejs
  - libffi
  - make
  - compilers
  - git
  - ca-certificates
  - openssl
  - readline
  - zlib
  - pkg-config
  - which
